name = "next-auth-cloudflare-d1-drizzle"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "example-db"
database_id = "3adec072-551b-4d08-aac9-f0954c5bb5b2"
preview_database_id = "DB" # Required for Pages local development

